name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  check-PR-and-commit-title:
    runs-on: ubuntu-latest
    steps:
      - name: title-verifier
        uses: Mustafakhn/pr-title-verifier-action@v2
    